loglist/loglist/urls.py
from django.contrib import admin
from django.urls import path, include
from loglist import *
from loglists import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('loglists.urls', namespace='loglists')),
]

loglist/loglists/urls.py
"""Defines url patterns for learning_logs."""

from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'logslists'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    path('posts/', views.posts, name='posts'),
    path('new_post/', views.new_post, name='new_post'),
    path('posts/<int:post_id>/', views.post, name='post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('posts/<str:tag_slug>', views.posts, name='post_list_by_tag'),
    ]
#    path('posts/<str:tag_slug>', views.posts, name="post_by_tags"),

loglist/loglists/models.py
from django.db import models
from taggit.managers import TaggableManager

# Create your models here.

class Post(models.Model):
    switch_ip = models.CharField("IP адресс оборудования", max_length=250)
    text = models.TextField("Список изменений")
    date_now = models.DateTimeField("Дата изменения", auto_now=True)
    tags = TaggableManager()
    def __str__(self):
        return self.switch_ip + " " + str(self.text)

loglist/loglists/forms.py
from django import forms
from .models import Post
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from django.urls import reverse

class PostForm(forms.ModelForm):
    switch_ip = forms.CharField(label='IP адрес',widget=forms.TextInput(attrs={'placeholder':'IP адрес'}))
    text = forms.CharField(label='описание',widget=forms.TextInput(attrs={'placeholder':'Описание'}))
    tags = forms.SelectMultiple()

    class Meta:
        model = Post
        fields = ['switch_ip','text']
        labels = {'': '',
                  '':''}

loglist/loglists/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Post
from .forms import PostForm #достаем из форм модель для формы нового поста
from django.core.paginator import Paginator #пагинация
from taggit.models import Tag
# Create your views here.

def index(request):
    """The home page for Learning Log."""
    return render(request, 'loglists/index.html') #возвращает шаблон главной страницы
def posts(request, tag_slug=None):
    object_list = Post.objects.order_by('-date_now')
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    context = {'object_list': object_list,
                'tag': tag}
    return render(request, 'loglists/topics.html', context)


def new_post(request):
    if request.method != 'POST':
        form = PostForm()
        #Данные не отправлялись, создаем пустую форму
    else:
        #POST запрос, обрабатываем
        form = PostForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('loglists:posts'))
    context = {'form': form}
    return render(request, 'loglists/new_post.html', context)



def post(request, post_id):
    """Show a single topic, and all its entries."""
    post = get_object_or_404(Post, id=post_id)
    posst = Post.objects.order_by('-date_now')
    context = {'posst': posst}
    return render(request, 'loglists/post.html', context)


def edit_post(request, post_id):
    post = Post.objects.get(id=post_id)

    if request.method == 'POST':
        form = PostForm(request.POST, instance = post)
        form.is_valid()
        form.save()
        return HttpResponseRedirect(reverse('loglists:posts'))

    else:
        form = PostForm(instance = post)
    context = {'form': form,
                'post': post,
                }
    context = {'post':post,
                'form': form}

    return render (request, 'loglists/edit_post.html', context)

loglist/loglists/templates/loglists/base.html
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

<!------ Include the above in your HEAD tag ---------->

<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url "loglists:index" %}">
          <i class="fa fa-home"></i>
          Главная
          <span class="sr-only">(current)</span>
          </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "loglists:posts"%}">
          <i class="fa fa-envelope-o">
            <span class="badge badge-danger">1</span>
          </i>
          Записи
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'loglists:new_post'%}">
          <i class="fa fa-plus">
            <span class="badge badge-danger"></span>
          </i>
          Добавить
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fa fa-bell">
            <span class="badge badge-info"></span>
          </i>
          Disabled
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fa fa-globe">
            <span class="badge badge-success"></span>
          </i>
          Disabled
        </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

</div>

  <div class="container">{% block content %}{% endblock content %}</div>


<style media="screen">
  @import url("//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css");

  body {
      background-color: #e6ecf0;
}
  .fa-plus {
    color: green;
  }
  .navbar-icon-top .navbar-nav .nav-link > .fa {
    position: relative;
    width: 36px;
    font-size: 24px;
  }

  .navbar-icon-top .navbar-nav .nav-link > .fa > .badge {
    font-size: 0.75rem;
    position: absolute;
    right: 0;
    font-family: sans-serif;
  }

  .navbar-icon-top .navbar-nav .nav-link > .fa {
    top: 3px;
    line-height: 12px;
  }

  .navbar-icon-top .navbar-nav .nav-link > .fa > .badge {
    top: -10px;
  }

  @media (min-width: 576px) {
    .navbar-icon-top.navbar-expand-sm .navbar-nav .nav-link {
      text-align: center;
      display: table-cell;
      height: 70px;
      vertical-align: middle;
      padding-top: 0;
      padding-bottom: 0;
    }

    .navbar-icon-top.navbar-expand-sm .navbar-nav .nav-link > .fa {
      display: block;
      width: 48px;
      margin: 2px auto 4px auto;
      top: 0;
      line-height: 24px;
    }

    .navbar-icon-top.navbar-expand-sm .navbar-nav .nav-link > .fa > .badge {
      top: -7px;
    }
  }

  @media (min-width: 768px) {
    .navbar-icon-top.navbar-expand-md .navbar-nav .nav-link {
      text-align: center;
      display: table-cell;
      height: 70px;
      vertical-align: middle;
      padding-top: 0;
      padding-bottom: 0;
    }

    .navbar-icon-top.navbar-expand-md .navbar-nav .nav-link > .fa {
      display: block;
      width: 48px;
      margin: 2px auto 4px auto;
      top: 0;
      line-height: 24px;
    }

    .navbar-icon-top.navbar-expand-md .navbar-nav .nav-link > .fa > .badge {
      top: -7px;
    }
  }

  @media (min-width: 992px) {
    .navbar-icon-top.navbar-expand-lg .navbar-nav .nav-link {
      text-align: center;
      display: table-cell;
      height: 70px;
      vertical-align: middle;
      padding-top: 0;
      padding-bottom: 0;
    }

    .navbar-icon-top.navbar-expand-lg .navbar-nav .nav-link > .fa {
      display: block;
      width: 48px;
      margin: 2px auto 4px auto;
      top: 0;
      line-height: 24px;
    }

    .navbar-icon-top.navbar-expand-lg .navbar-nav .nav-link > .fa > .badge {
      top: -7px;
    }
  }

  @media (min-width: 1200px) {
    .navbar-icon-top.navbar-expand-xl .navbar-nav .nav-link {
      text-align: center;
      display: table-cell;
      height: 70px;
      vertical-align: middle;
      padding-top: 0;
      padding-bottom: 0;
    }

    .navbar-icon-top.navbar-expand-xl .navbar-nav .nav-link > .fa {
      display: block;
      width: 48px;
      margin: 2px auto 4px auto;
      top: 0;
      line-height: 24px;
    }

    .navbar-icon-top.navbar-expand-xl .navbar-nav .nav-link > .fa > .badge {
      top: -7px;
    }
  }

</style>

loglist/loglists/templates/loglists/edit_post.html
{% extends 'loglists/base.html' %}

{% load crispy_forms_tags %}




<div class="container">
  {% block content %}
<form class="add col-md-12" method="post" novalidate>
  {% csrf_token %}
    <div class="form-group">
      {{ form.switch_ip|as_crispy_field }}
    </div>
    <div class="form-group">
      {{ form.text|as_crispy_field }}
    </div>
<button type="submit" class="btn btn-primary mb-2">Редактировать</button>
</form>
<style media="screen">
.asteriskField {
    display: none;
}
.add {
margin: 0 auto;
}

#id_tags {
height: 150px;
}
</style>
{% endblock %}
</div>

loglist/loglists/templates/loglists/index.html
{% extends 'loglists/base.html' %}


  {% block content %}
asd
{% endblock content %}

loglist/loglists/templates/loglists/new_post.html
{% extends 'loglists/base.html' %}

{% load crispy_forms_tags %}




<div class="container">
  {% block content %}
<form class="add col-md-12" method="post" novalidate>
  {% csrf_token %}
    <div class="form-group">
      {{ form.switch_ip|as_crispy_field }}
    </div>
    <div class="form-group">
      {{ form.text|as_crispy_field }}
    </div>
<button type="submit" class="btn btn-primary mb-2">Добавить</button>
</form>
<style media="screen">
.asteriskField {
    display: none;
}
.add {
margin: 0 auto;
}

#id_tags {
height: 150px;
}
</style>
{% endblock %}
</div>

loglist/loglists/templates/loglists/tag_detail.html
{% extends 'loglists/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3 left-frame">
            <div class="col-md-12 first-block">
                <ul>
              <li><a href="#"><i class="fas fa-plus plus"></i> Добавить запись</a></li>
             </ul>
            </div>
            <div class="col-md-12 second-block">
                <li><a href="{% url 'loglists:posts' %}">Все города</a></li>
                {%for tag in tags%}
                    <li><a href="{% url 'loglists:tag_detail' tag.slug %}">{{tag.title}}</a></li>
                {%endfor%}
            </div>
        </div>

        <div class="col-lg-8">
{% for post in tag.posts.all %}
          <div class="post">
        <div class="post-container">
            <div class="post-header col-md-4"><a href="+">Xmahop</a></div>
                <div class="post-date col-md-12"><p>{{post.date_now}}</p></div>
            <div class="post-title col-md-8"><a href="#">{{post.switch_ip}}</a></div>
            <div class="post-text col-md-12">{{post.text}}</div>
            <div class="post-edit col-md-3"><a href="{% url 'loglists:edit_post' post.id %}"><i class="fas fa-edit"></i></a></div>
            <div class="post-line col-md-8"></div>
        </div>
      </div>
{% empty %}
    <li>no tags added</li>
{% endfor %}
</div>
<style>
     body {
    color: #14171a;
    font-size: 14px;
  }
  body a {
    color: #30a4f2;
  }
  body a:hover {
    text-decoration: none;
  }

  li {
  list-style-type: none;
  }
  .post:hover {
    background-color: #f5f8fa;
  }
  .post {
    background-color: #fff;
    margin: 0 auto;

  }
  .post-container {
    padding-top: 1%;
  }
  .post-name {
    color: #14171a;
    font-size: 15px;
    font-weight: bold;
  }
  .post-title {
    padding-right: 40px;
    font-weight: bold;
    font-size: 14px;
  }
  .container {
    padding-top: 30px;
  }

  .post-header a {
    font-size: 14px;
  }
  .post-header p {
    color: #657786;
    font-size: 14px;
  }
  .post-line {
  margin-top:20px;
  border-top:1px solid #e6ecf0;
  min-width: 130%;
  margin-left: -40px;

  }
  .post-edit {
    margin-top: 8px;
    font-size: 20px;
  }
  .pagination {
    width/max-width: 800px;
    margin: 0 auto;
  }

  .left-frame {
  height: 350px;
postition: relative;
z-index: 999999;
}


.left-frame ul {
margin-left: -40px;
padding-top: 10%;
}
.pag {
margin: 0 auto;
z-index: 999999;
}

.fa-plus {
color: #30a4f2 !important;
}
.left-side {
margin-top:
}
.first-block {
background-color: #fff;
height: 50%;
width: 100%;
}

.second-block {
margin-top: 3%;
background-color: #fff;
}


.post-date p{
display: inline;
}
</style>
{% endblock %}

loglist/loglists/templates/loglists/tag_list.html
{% extends 'loglists/base.html' %}

{% block content %}
<h1>Все теги</h1>
{{tags.title}}
{% for tag in tags %}
    <li><a href="{{tag.slug}}">{{tag}}</a></li>
{% empty %}
    <li>no tags added</li>
{% endfor %}

{% endblock %}

loglist/loglists/templates/loglists/topics.html
{% extends "loglists/base.html" %}

{% block content %}

<div class="container">


    <div class="row">
        <div class="col-md-3 left-frame">
            <div class="col-md-12 first-block">
                <ul>
              <li><a href="#"><i class="fas fa-plus plus"></i> Добавить запись</a></li>
             </ul>
            </div>
            <div class="col-md-12 second-block">
                {% for post in object_list %}
                   {{ post.tags.all|join:" " }}
                {%endfor %}
            </div>
        </div>

        <div class="col-lg-8">

{% for post in object_list %}
      <div class="post">
        <div class="post-container">
            <div class="post-header col-md-4"><a href="+">Xmahop</a></div>
            <div class="post-date col-md-12">
                {% for tag in post.tags.all %}
                    <a href="{% url "loglists:post_list_by_tag" tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
                @ <p>{{post.date_now}}</p>
            </div>
            <div class="post-title col-md-8"><a href="#">{{post.switch_ip}}</a></div>
            <div class="post-text col-md-12">{{post.text}}</div>
            <div class="col-md-12">
            <div class="post-edit col-md-3"><a href="{% url 'loglists:edit_post' post.id %}"><i class="fas fa-edit"></i></a></div>
            <div class="post-line col-md-8"></div>
        </div>
      </div>
{% empty %}
            asdasd
{% endfor %}
        </div>
    </div>
    </div> <!-- /container -->

<div class="container">
    <div class="col-md-3 pag">
<nav aria-label="...">
  <ul class="pagination">

</div>
</div>
</div>
<style>
  body {
    color: #14171a;
    font-size: 14px;
  }
  body a {
    color: #30a4f2;
  }
  body a:hover {
    text-decoration: none;
  }

  li {
  list-style-type: none;
  }
  .post:hover {
    background-color: #f5f8fa;
  }
  .post {
    background-color: #fff;
    margin: 0 auto;

  }
  .post-container {
    padding-top: 1%;
  }
  .post-name {
    color: #14171a;
    font-size: 15px;
    font-weight: bold;
  }
  .post-title {
    padding-right: 40px;
    font-weight: bold;
    font-size: 14px;
  }
  .container {
    padding-top: 30px;
  }

  .post-header a {
    font-size: 14px;
  }
  .post-header p {
    color: #657786;
    font-size: 14px;
  }
  .post-line {
  margin-top:20px;
  border-top:1px solid #e6ecf0;
  min-width: 130%;
  margin-left: -40px;

  }
  .post-edit {
    margin-top: 8px;
    font-size: 20px;
  }
  .pagination {
    width/max-width: 800px;
    margin: 0 auto;
  }

  .left-frame {
  height: 350px;
postition: relative;
z-index: 999999;
}


.left-frame ul {
margin-left: -40px;
padding-top: 10%;
}
.pag {
margin: 0 auto;
z-index: 999999;
}

.fa-plus {
color: #30a4f2 !important;
}
.left-side {
margin-top:
}
.first-block {
background-color: #fff;
height: 50%;
width: 100%;
}

.second-block {
margin-top: 3%;
background-color: #fff;
}


.post-date p{
display: inline;
}
</style>
{%endblock content%}